services:
  - type: web
    name: quiz
    runtime: docker
    repo: https://github.com/masarukun3113/quiz.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
